[build]
  base = "react-native-orange-chatt-----inProgres"
  command = "npm run build"
  publish = "web-build"
  environment = { NODE_VERSION = "18" }


[[redirects]]
from = "/*"
to = "index.html"
status = 200